insert into drugs (name, generic, form, strength, tags) values
    ('Crocin', 'paracetamol', 'tab', '500mg', '{otc,pain,fever}'),
    ('Crocin Advance', 'paracetamol', 'tab', '500mg', '{otc,pain,fever}'),
    ('Dolo 650', 'paracetamol', 'tab', '650mg', '{pain,fever}'),
    ('Calpol', 'paracetamol', 'tab', '500mg', '{otc,pain,fever}'),
    ('Calpol 250 Syrup', 'paracetamol', 'syrup', '250mg/5ml', '{otc,pain,fever,paediatric}'),
    ('Brufen', 'ibuprofen', 'tab', '400mg', '{pain,fever,antiinflammatory}'),
    ('Combiflam', 'ibuprofen + paracetamol', 'tab', '400mg+325mg', '{pain,fever}'),
    ('Meftal Spas', 'mefenamic acid + dicyclomine', 'tab', '250mg+10mg', '{pain,cramps}'),
    ('Meftal P Syrup', 'mefenamic acid', 'syrup', '100mg/5ml', '{pain,fever,paediatric}'),
    ('Voveran', 'diclofenac', 'tab', '50mg', '{pain,antiinflammatory}'),
    ('Augmentin 625', 'amoxicillin + clavulanate', 'tab', '625mg', '{antibiotic}'),
    ('Augmentin Duo Syrup', 'amoxicillin + clavulanate', 'syrup', '400mg+57mg/5ml', '{antibiotic,paediatric}'),
    ('Mox 500', 'amoxicillin', 'cap', '500mg', '{antibiotic}'),
    ('Moxikind CV 625', 'amoxicillin + clavulanate', 'tab', '625mg', '{antibiotic}'),
    ('Azithral 500', 'azithromycin', 'tab', '500mg', '{antibiotic}'),
    ('Azee 500', 'azithromycin', 'tab', '500mg', '{antibiotic}'),
    ('Monocef 1g', 'ceftriaxone', 'inj', '1g', '{antibiotic}'),
    ('Taxim O 200', 'cefixime', 'tab', '200mg', '{antibiotic}'),
    ('Cifran 500', 'ciprofloxacin', 'tab', '500mg', '{antibiotic}'),
    ('Levoflox 500', 'levofloxacin', 'tab', '500mg', '{antibiotic}'),
    ('Cefopod 200', 'cefpodoxime', 'tab', '200mg', '{antibiotic}'),
    ('Metrogyl 400', 'metronidazole', 'tab', '400mg', '{antibiotic}'),
    ('Pantocid 40', 'pantoprazole', 'tab', '40mg', '{acidity,ppi}'),
    ('Pan D', 'pantoprazole + domperidone', 'cap', '40mg', '{acidity,ppi}'),
    ('Pan 40', 'pantoprazole', 'tab', '40mg', '{acidity,ppi}'),
    ('Nexpro 40', 'esomeprazole', 'tab', '40mg', '{acidity,ppi}'),
    ('Razo 20', 'rabeprazole', 'tab', '20mg', '{acidity,ppi}'),
    ('Gelusil MPS', 'aluminium hydroxide + magnesium hydroxide + simethicone', 'syrup', '200ml', '{otc,acidity}'),
    ('Digene Gel', 'aluminium hydroxide + magnesium hydroxide', 'syrup', '200ml', '{otc,acidity}'),
    ('Ondem', 'ondansetron', 'tab', '4mg', '{antiemetic}'),
    ('Domstal', 'domperidone', 'tab', '10mg', '{antiemetic}'),
    ('Rantac 150', 'ranitidine', 'tab', '150mg', '{acidity}'),
    ('Cetrizine', 'cetirizine', 'tab', '10mg', '{otc,allergy}'),
    ('Alerid', 'cetirizine', 'tab', '10mg', '{otc,allergy}'),
    ('Montair LC', 'montelukast + levocetirizine', 'tab', '10mg+5mg', '{allergy,asthma}'),
    ('Montek LC', 'montelukast + levocetirizine', 'tab', '10mg+5mg', '{allergy,asthma}'),
    ('Avil 25', 'pheniramine', 'tab', '25mg', '{allergy}'),
    ('Allegra 120', 'fexofenadine', 'tab', '120mg', '{allergy}'),
    ('Okacet', 'cetirizine', 'tab', '10mg', '{otc,allergy}'),
    ('Ascoril LS', 'ambroxol + levosalbutamol + guaifenesin', 'syrup', '100ml', '{cough}'),
    ('Ascoril D', 'dextromethorphan + phenylephrine + chlorpheniramine', 'syrup', '100ml', '{cough,cold}'),
    ('Benadryl', 'diphenhydramine', 'syrup', '100ml', '{otc,cough}'),
    ('Corex', 'codeine + chlorpheniramine', 'syrup', '100ml', '{cough}'),
    ('Sinarest', 'paracetamol + phenylephrine + chlorpheniramine', 'tab', '500mg+10mg+2mg', '{otc,cold}'),
    ('D-Cold Total', 'paracetamol + phenylephrine + caffeine + chlorpheniramine', 'tab', '500mg+5mg+30mg+2mg', '{otc,cold}'),
    ('Vicks Action 500', 'paracetamol + phenylephrine + caffeine', 'tab', '500mg+10mg+32mg', '{otc,cold}'),
    ('Otrivin Nasal Drops', 'xylometazoline', 'drops', '0.1%', '{otc,cold}'),
    ('Nasivion', 'oxymetazoline', 'drops', '0.05%', '{otc,cold}'),
    ('Glycomet 500', 'metformin', 'tab', '500mg', '{diabetes}'),
    ('Glycomet SR 500', 'metformin', 'tab', '500mg', '{diabetes}'),
    ('Glycomet SR 1g', 'metformin', 'tab', '1g', '{diabetes}'),
    ('Glimepiride 1', 'glimepiride', 'tab', '1mg', '{diabetes}'),
    ('Janumet 50/500', 'sitagliptin + metformin', 'tab', '50mg+500mg', '{diabetes}'),
    ('Galvus Met 50/500', 'vildagliptin + metformin', 'tab', '50mg+500mg', '{diabetes}'),
    ('Lantus', 'insulin glargine', 'inj', '100iu/ml', '{diabetes,cold-chain}'),
    ('Actrapid', 'insulin regular', 'inj', '100iu/ml', '{diabetes,cold-chain}'),
    ('Amaryl M 1', 'glimepiride + metformin', 'tab', '1mg+500mg', '{diabetes}'),
    ('Atorva 10', 'atorvastatin', 'tab', '10mg', '{cholesterol,cardiac}'),
    ('Atorva 20', 'atorvastatin', 'tab', '20mg', '{cholesterol,cardiac}'),
    ('Rosuvas 10', 'rosuvastatin', 'tab', '10mg', '{cholesterol,cardiac}'),
    ('Ecosprin 75', 'aspirin', 'tab', '75mg', '{cardiac,otc}'),
    ('Ecosprin AV 75', 'aspirin + atorvastatin', 'cap', '75mg+10mg', '{cardiac,cholesterol}'),
    ('Clopilet 75', 'clopidogrel', 'tab', '75mg', '{cardiac}'),
    ('Telma 40', 'telmisartan', 'tab', '40mg', '{bp,cardiac}'),
    ('Telma AM', 'telmisartan + amlodipine', 'tab', '40mg+5mg', '{bp,cardiac}'),
    ('Amlong 5', 'amlodipine', 'tab', '5mg', '{bp,cardiac}'),
    ('Concor 5', 'bisoprolol', 'tab', '5mg', '{bp,cardiac}'),
    ('Met XL 25', 'metoprolol', 'tab', '25mg', '{bp,cardiac}'),
    ('Losar H', 'losartan + hydrochlorothiazide', 'tab', '50mg+12.5mg', '{bp,cardiac}'),
    ('Lasix 40', 'furosemide', 'tab', '40mg', '{diuretic}'),
    ('Thyronorm 50', 'levothyroxine', 'tab', '50mcg', '{thyroid}'),
    ('Thyronorm 100', 'levothyroxine', 'tab', '100mcg', '{thyroid}'),
    ('Eltroxin 100', 'levothyroxine', 'tab', '100mcg', '{thyroid}'),
    ('Prednisolone 5', 'prednisolone', 'tab', '5mg', '{steroid}'),
    ('Wysolone 10', 'prednisolone', 'tab', '10mg', '{steroid}'),
    ('Omnacortil 20', 'prednisolone', 'tab', '20mg', '{steroid}'),
    ('Depo Medrol', 'methylprednisolone', 'inj', '40mg', '{steroid}'),
    ('Budecort Inhaler', 'budesonide', 'inhaler', '200mcg', '{asthma}'),
    ('Asthalin Inhaler', 'salbutamol', 'inhaler', '100mcg', '{asthma}'),
    ('Foracort 200 Inhaler', 'formoterol + budesonide', 'inhaler', '6mcg+200mcg', '{asthma}'),
    ('Seroflo 250', 'salmeterol + fluticasone', 'inhaler', '25mcg+250mcg', '{asthma}'),
    ('Calcirol Sachet', 'cholecalciferol', 'drops', '60000iu', '{otc,vitamin}'),
    ('Shelcal 500', 'calcium carbonate + vitamin d3', 'tab', '500mg+250iu', '{otc,vitamin}'),
    ('Becosules Z', 'vitamin b complex + zinc', 'cap', '', '{otc,vitamin}'),
    ('Neurobion Forte', 'b1 + b6 + b12', 'tab', '', '{otc,vitamin}'),
    ('Limcee', 'vitamin c', 'tab', '500mg', '{otc,vitamin}'),
    ('Zincovit', 'multivitamin + zinc', 'tab', '', '{otc,vitamin}'),
    ('Revital H', 'multivitamin + ginseng', 'cap', '', '{otc,vitamin}'),
    ('ORS', 'oral rehydration salts', 'powder', '21.8g', '{otc,rehydration}'),
    ('Electral', 'oral rehydration salts', 'powder', '21.8g', '{otc,rehydration}'),
    ('Dulcolax 5', 'bisacodyl', 'tab', '5mg', '{otc,laxative}'),
    ('Cremaffin', 'milk of magnesia + liquid paraffin', 'syrup', '225ml', '{otc,laxative}'),
    ('Udiliv 300', 'ursodeoxycholic acid', 'tab', '300mg', '{liver}'),
    ('Livogen', 'iron + folic acid', 'tab', '', '{otc,haematinic}'),
    ('Orofer XT', 'iron + folic acid', 'tab', '', '{haematinic}'),
    ('Dexorange', 'iron + b12 + folic acid', 'syrup', '200ml', '{otc,haematinic}'),
    ('Sporlac DS', 'lactobacillus', 'tab', '', '{otc,probiotic}'),
    ('Enterogermina', 'bacillus clausii', 'drops', '5ml', '{otc,probiotic}'),
    ('Volini Gel', 'diclofenac', 'gel', '30g', '{otc,pain,topical}'),
    ('Moov', 'methyl salicylate + menthol + eucalyptus', 'cream', '30g', '{otc,pain,topical}'),
    ('Soframycin Skin Cream', 'framycetin', 'cream', '30g', '{otc,antibiotic,topical}'),
    ('Betnovate N', 'betamethasone + neomycin', 'cream', '20g', '{topical,steroid}'),
    ('Candid B', 'clotrimazole + beclomethasone', 'cream', '15g', '{antifungal,topical}'),
    ('Clotrimazole Cream', 'clotrimazole', 'cream', '15g', '{otc,antifungal,topical}')
on conflict do nothing;

insert into pharmacies (name, phone, address, city, state, country, location, verified) values
    ('Apollo Pharmacy', '+91-11-40050505', '21 Connaught Place', 'New Delhi', 'DL', 'IN', st_makepoint(77.2193, 28.6328)::geography, true),
    ('1mg Store', '+91-11-40055050', '17 Karol Bagh', 'New Delhi', 'DL', 'IN', st_makepoint(77.1906, 28.6519)::geography, true),
    ('MedPlus', '+91-11-45001100', '5 Saket PVR', 'New Delhi', 'DL', 'IN', st_makepoint(77.2047, 28.5275)::geography, false),
    ('Guardian Pharmacy', '+91-11-43012222', 'Select Citywalk', 'New Delhi', 'DL', 'IN', st_makepoint(77.2193, 28.528)::geography, false),
    ('Netmeds', '+91-11-49999999', '12 Lajpat Nagar', 'New Delhi', 'DL', 'IN', st_makepoint(77.2356, 28.5672)::geography, false),
    ('Wellness Forever', '+91-22-12345678', 'Bandra West', 'Mumbai', 'MH', 'IN', st_makepoint(72.8296, 19.0596)::geography, false),
    ('Trust Pharmacy', '+91-80-22345678', 'Indiranagar 100ft Rd', 'Bengaluru', 'KA', 'IN', st_makepoint(77.6408, 12.9784)::geography, false)
on conflict do nothing;
